package org.openmrs.module.esaudereports.reports.mmia.util;

public interface MmiaSqlSource {
	
	String SQL_FIND_NEW_ENROLLED_PATIENT_BY_PERIOD = "select count(distinct patient_program.patient_id) from  patient_program "
	        + " join program on program.program_id = patient_program.program_id"
	        + " where program.uuid ='efe2481f-9e75-4515-8d5a-86bfde2b5ad3' "
	        + "and voided is false"
	        + " and patient_program.date_enrolled BETWEEN :startDate and :endDate";
	
	String SQL_FIND_CHANGED_PATIENT_BY_PERIOD = "select count(distinct patient_program.patient_id) from  patient_program "
	        + " join program on program.program_id = patient_program.program_id"
	        + " where program.uuid ='efe2481f-9e75-4515-8d5a-86bfde2b5ad3' "
	        + "and voided is false and patient_program.date_changed is not null "
	        + " and patient_program.date_changed BETWEEN :startDate and :endDate";
	
	String SQL_FIND_MAINTAINING_PATIENTS_BEFORE_PERIOD = "select count(distinct patient_program.patient_id) from  patient_program "
	        + " join program on program.program_id = patient_program.program_id "
	        + " where program.uuid ='efe2481f-9e75-4515-8d5a-86bfde2b5ad3' "
	        + " and voided is false "
	        + " and patient_program.date_enrolled < :startDate";
	
	String SQL_FIND_ART_REGIMENS = "select distinct concept_name.name as 'REGIMEN', count(distinct obs.person_id) as 'NUM_PATIENTS' from phm_drug_regime "
	        + " join obs on (obs.concept_id = 1088 and obs.value_coded = phm_drug_regime.regime_id)"
	        + " join concept_name on (concept_name.concept_id = phm_drug_regime.regime_id)" + " group by obs.value_coded ";
	
	String SQL_FIND_BALANCETE_BY_PERIOD = " select ENTRADAS.fnm as 'FNM',"
	        + " ENTRADAS.name as 'NAME',"
	        + " ENTRADAS.OUTPUT_UNIT,"
	        + " coalesce(SALDO_INICIAL.value, 0) as 'INITIAL_BALANCE',"
	        + " coalesce(ENTRADAS.value, 0) as 'ENTRANCES',"
	        + " coalesce(SAIDAS.value, 0) as 'EXITS',"
	        + " coalesce(AJUSTES_POSETIVO.value, 0) as 'POSETIVE_ADJUSTS',"
	        + " coalesce(AJUSTES_NEGATIVO.value, 0) as 'NEGATIVE_ADJUSTS',"
	        + " (coalesce(SALDO_INICIAL.value, 0) + coalesce(ENTRADAS.value, 0) + coalesce(AJUSTES_POSETIVO.value, 0) - coalesce(SAIDAS.value, 0) - coalesce(AJUSTES_NEGATIVO.value, 0)) as 'CURRENT_BALANCE', "
	        + "  DATE_FORMAT(ENTRADAS.VALIDITY,'%d/%m/%Y') "
	        + " from"
	        + " (select drugItem.fnm_code as 'FNM', d.name as 'NAME', package.total_quantity as 'OUTPUT_UNIT', sum(batchEntry.quantity) as 'VALUE', max(batch.expire_date) as 'VALIDITY' from drug d"
	        + " join phm_drug_items drugItem on drugItem.drug_id = d.drug_id"
	        + "	join pocinv_drug_package package on package.drug_id = d.drug_id"
	        + "	join pocinv_batch batch on batch.drug_package_id = package.drug_package_id"
	        + "	join pocinv_batch_entry batchEntry on batchEntry.batch_id = batch.batch_id"
	        + "	where batchEntry.batch_operation_type = 'RECEIPT'"
	        + " and batchEntry.date_created BETWEEN :startDate and :endDate"
	        + " group by  drugItem.fnm_code"
	        + " ) ENTRADAS"
	        + " left join"
	        + " (select drugItem.fnm_code as 'FNM', d.name as 'NAME', package.total_quantity as 'OUTPUT_UNIT', sum(batchEntry.quantity) as 'VALUE', max(batch.expire_date) as 'VALIDITY' from drug d"
	        + " join phm_drug_items drugItem on drugItem.drug_id = d.drug_id"
	        + " join pocinv_drug_package package on package.drug_id = d.drug_id"
	        + " left join pocinv_batch batch on batch.drug_package_id = package.drug_package_id"
	        + " left join pocinv_batch_entry batchEntry on batchEntry.batch_id = batch.batch_id"
	        + " where batchEntry.batch_operation_type = 'DISTRIBUTION'"
	        + " and batchEntry.date_created  BETWEEN :startDate and :endDate"
	        + " group by  drugItem.fnm_code"
	        + " ) SAIDAS"
	        + " on ENTRADAS.FNM = SAIDAS.FNM"
	        + " left join"
	        + " (select drugItem.fnm_code as 'FNM', d.name as 'NAME', package.total_quantity as 'OUTPUT_UNIT', sum(batchEntry.quantity) as 'VALUE', max(batch.expire_date) as 'VALIDITY' from drug d"
	        + " join phm_drug_items drugItem on drugItem.drug_id = d.drug_id"
	        + " join pocinv_drug_package package on package.drug_id = d.drug_id"
	        + " left join pocinv_batch batch on batch.drug_package_id = package.drug_package_id"
	        + " left join pocinv_batch_entry batchEntry on batchEntry.batch_id = batch.batch_id"
	        + " where batchEntry.batch_operation_type = 'POSETIVE_ADJUSTMENT'"
	        + " and batchEntry.date_created  BETWEEN :startDate and :endDate"
	        + " group by  drugItem.fnm_code"
	        + " ) AJUSTES_POSETIVO"
	        + " on ENTRADAS.FNM = AJUSTES_POSETIVO.FNM"
	        + " left join"
	        + " (select drugItem.fnm_code as 'FNM', d.name as 'NAME', package.total_quantity as 'OUTPUT_UNIT', sum(batchEntry.quantity) as 'VALUE', max(batch.expire_date) as 'VALIDITY' from drug d"
	        + " join phm_drug_items drugItem on drugItem.drug_id = d.drug_id"
	        + " join pocinv_drug_package package on package.drug_id = d.drug_id"
	        + " left join pocinv_batch batch on batch.drug_package_id = package.drug_package_id"
	        + " left join pocinv_batch_entry batchEntry on batchEntry.batch_id = batch.batch_id"
	        + " where batchEntry.batch_operation_type = 'NEGATIVE_ADJUSTMENT'"
	        + " and batchEntry.date_created  BETWEEN :startDate and :endDate"
	        + " group by  drugItem.fnm_code"
	        + " ) AJUSTES_NEGATIVO"
	        + " on ENTRADAS.FNM = AJUSTES_NEGATIVO.FNM"
	        + " left join"
	        + " (select entradaInicial.fnm as 'FNM', entradaInicial.nome as 'NAME', entradaInicial.OUTPUT_UNIT, (coalesce(entradaInicial.value, 0) - coalesce(saidaInicial.value, 0))  as 'VALUE', 'VALIDITY' from"
	        + " (select drugItem.fnm_code as 'FNM', d.name nome, package.total_quantity as 'OUTPUT_UNIT', sum(batchEntry.quantity) as 'value', batch.batch_id, max(batch.expire_date) as 'VALIDITY' from drug d"
	        + " join phm_drug_items drugItem on drugItem.drug_id = d.drug_id"
	        + " join pocinv_drug_package package on package.drug_id = d.drug_id"
	        + " join pocinv_batch batch on batch.drug_package_id = package.drug_package_id"
	        + " join pocinv_batch_entry batchEntry on batchEntry.batch_id = batch.batch_id"
	        + " where batchEntry.batch_operation_type in('RECEIPT','POSETIVE_ADJUSTMENT')"
	        + " and batchEntry.date_created  < :startDate"
	        + " group by drugItem.fnm_code"
	        + " ) entradaInicial"
	        + " left join"
	        + " (select drugItem.fnm_code as 'FNM', d.name as 'NAME', package.total_quantity as 'OUTPUT_UNIT', sum(batchEntry.quantity) as 'VALUE', max(batch.expire_date) as 'VALIDITY' from drug d"
	        + " join phm_drug_items drugItem on drugItem.drug_id = d.drug_id"
	        + " join pocinv_drug_package package on package.drug_id = d.drug_id"
	        + " join pocinv_batch batch on batch.drug_package_id = package.drug_package_id"
	        + " join pocinv_batch_entry batchEntry on batchEntry.batch_id = batch.batch_id"
	        + " where batchEntry.batch_operation_type in('DISTRIBUTION','NEGATIVE_ADJUSTMENT')"
	        + " and batchEntry.date_created  < :startDate" + " group by  drugItem.fnm_code" + " ) saidaInicial"
	        + " on entradaInicial.fnm = saidaInicial.fnm" + "	) SALDO_INICIAL" + " on ENTRADAS.fnm = SALDO_INICIAL.fnm";
	
}
